service: serverless-fastapi

useDotenv: true

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    PORT: ${env:PORT}
    PROJECT_ENVIRONMENT: ${env:PROJECT_ENVIRONMENT}
    API_HOST: ${env:API_HOST}

package:
  exclude:
    - Makefile
    - poetry.lock
    - README.md
    - tests/**
    - docs/**
    - node_modules/**
    - .venv/**
    - .serverless/**
    - package.json
    - package-lock.json
    - .pytest_cache
    - .hypothesis

functions:
  api:
    handler: app.main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: "{proxy+}"
