service: serverless-fastapi

useDotenv: true

plugins:
  - serverless-python-requirements
  - serverless-localstack

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    PORT: ${env:PORT}
    PROJECT_ENVIRONMENT: ${env:PROJECT_ENVIRONMENT}
    API_HOST: ${env:API_HOST}

package:
  exclude:
    - Makefile
    - poetry.lock
    - README.md
    - tests/*
    - docs/*
    - node_modules/*
    - .venv/*
    - .serverless/*
    - package.json
    - package-lock.json
    - .pytest_cache
    - .hypothesis

custom:
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    strip: true
    layer:
      name: PythonRequirementsLambdaLayer
      description: Python requirements layer
      compatibleRuntimes:
        - python3.11

functions:
  api:
    handler: app.server.app.handler
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: "{proxy+}"
