service: serverless-fastapi

plugins:
  - serverless-python-requirements
provider:
  name: aws
  runtime: python3.11
  region: us-east-1

package:
  exclude:
    - Makefile
    - poetry.lock
    - README.md
    - tests/**
    - docs/**
    - node_modules/**
    - .venv/**
    - .serverless/**
    - package.json
    - package-lock.json
    - .pytest_cache
    - .hypothesis

functions:
  api:
    handler: app.main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: "{proxy+}"
