name: FastAPI CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    env:
      PORT: ${{ secrets.PORT }}
      PROJECT_ENVIRONMENT: ${{ secrets.PROJECT_ENVIRONMENT }}
      API_HOST: ${{ secrets.API_HOST }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.13

      - name: Install NodeJS for serverless framework
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Installing Serverless framework and plugins
        run: make serverless

      - name: Installing dependencies
        run: make deps

      - name: Black code style check
        run: make black

      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}

      - name: CI
        run: make ci

      - name: CD
        run: make cd
